all: main

main:
	$(MAKE) -C syntax
	$(MAKE) -C net

clean:
	$(MAKE) -C syntax clean
	$(MAKE) -C net clean

publish:
	rmdir /s /q release\win
	mkdir release\win
	mkdir release\win\tool
	mkdir release\win\parser
	copy net\bin\noogle.exe release\win\tool\\
	copy syntax\noogle.dll release\win\parser\\
	copy version release\win\\
